# Generated by Django 5.0.4 on 2024-04-23 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='comapny',
            new_name='company',
        ),
    ]
